# Enable mouse mode
set -g mouse on
unbind -T root M-MouseDown3Pane
unbind -T root MouseDown3Pane
unbind -T root MouseDown3Status

# Configure the tmux plugin manager
set -g @plugin 'tmux-plugins/tpm'

# Some sensible defaults for tmux
set -g @plugin 'tmux-plugins/tmux-sensible'

# Clipboard support
set -g @plugin 'tmux-plugins/tmux-yank'

# Prefix VIMKEYS to navigate and resize windows
set -g @pane_resize '2'
set -g @plugin 'tmux-plugins/tmux-pain-control'

# MUST BE LAST IN THE FILE
run '~/.tmux/plugins/tpm/tpm'
